[project]
name = "bbc_news_mcp_server_demo"
version = "0.1.0"
description = "An example MCP Server utilising FastMCP and feedparser to inject BBC articles into Claude Desktop"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.11",
    "mcp[cli]>=1.6.0",
]
